services:
  snapserver:
    image: pinkynrg/snapserver:latest
    container_name: snapserver
    ports:
      - 1704:1704
      - 1705:1705
      - 1780:1780
    environment:
      - DEVICE_NAME=Snapcast
      - CACHE=/data
    volumes:
      - /mnt/data/snapserver:/data
    restart: always
