services:
  snapclient:
    image: pinkynrg/snapclient:latest
    hostname: XXX-speaker
    container_name: snapclient
    devices:
      - /dev/snd:/dev/snd
    command: ["snapclient", "-h", "snapcast.francescomeli.com", "-s", "default:CARD=Headphones", "--hostID", "XXX-speaker"]
    restart: always